# Generated by Django 3.2.9 on 2022-02-16 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('date_of_birth', models.DateField(blank=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
            ],
        ),
    ]
